version: '3'
services:
    webapp:
        restart: always
        build:
           context: ./app
           dockerfile: Dockerfile.dev
        container_name: webapp_container
        ports:
          - "4000:5000"
        depends_on: 
            - webapp_db
        volumes:
          - ./app:/app


    webapp_db:
         restart: always
         image: mysql:5.7
         environment:
              MYSQL_ROOT_PASSWORD: root
         container_name: webapp_db_container
         volumes:
           - ./db:/docker-entrypoint-initdb.d/
         ports:
          - "3306:3306"


